name: reuse
on:
  workflow_call:
    inputs:
      flavor-town:
        required: false
        description: "flavor town"
        type: string

jobs:
  flavor-town:
    runs-on: Chris
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'kelleychris11/reusable'
          path: actions
      - name: flava-town
        run: echo "now THAT'S flavor town!!"
      - name: Current Directory
        run: pwd
      - name: Change Dir
        run: echo ${{ github.workspace }}